### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by quantitative-technologies** [evmcheb/friendrekt#1]
I'm trying to get started in MEV, and I've never used Rust, but: Is this complete code?

I only see one rust file build.rs with 10 lines of code.

Build and deploy hints would be very useful in case you have time for that.

**Comment by ZaneH** [comment]
The majority of the logic is in [main.rs](https://github.com/evmcheb/friendrekt/blob/main/friendrekt-rs/src/main.rs). It may be helpful to read through [this Twitter thread](https://twitter.com/evmcheb/status/1694614245516955709?s=20) to understand why the code in `main.rs` will no longer work in its current state.

TL;DR: Reading pending transactions from the mempool was patched ([code that reads from mempool](https://github.com/evmcheb/friendrekt/blob/0a0045152a057dfb59d8fd211a1631ceec5bb6e7/friendrekt-rs/src/main.rs#L273-L281))

I believe this code is meant more-so for reference to build your own tool. It's still possible to listen for transactions after they've been included in the block (and use the majority of this code) but as [evmcheb points out](https://twitter.com/evmcheb/status/1694625382904021246?s=20) the "main edge" was recently patched, so it will need modifications.

To run a Rust project, `cd` into the directory and run...

```bash
$ cargo install --path .
$ cargo run src/main.rs
```

I'm learning myself, so please take what I said with a grain of salt.

**Comment by ZaneH** [comment]
I'm trying to reimplement this repository as a learning exercise [here](https://github.com/buidlcat/friendrekt). I'm also writing about what I've learned [here](https://github.com/buidlcat/friendrekt/blob/main/BREAKDOWN.md).

**Comment by quantitative-technologies** [comment]
Thanks for elaborating!

**Comment by evmcheb** [comment]
Thanks @ZaneH , your remake looks great. To respond to your blog post
>I imagine the FIFOCache should be more than 10 entries. 100 or 1,000 wouldn’t take that much more memory and would increase the odds of finding a target quickly.

The FIFOCache is to de-duplicate the 5 websocket streams (there are a few blast-api backend nodes each with separate mempools). You're right though, this could be 100 or 1000. 
Feel free to reach out on twitter if you have any more questions
